// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbeCKMZPzsUt_Ru9Z-YFkqvf_ORxXfX60',
    appId: '1:925330772922:web:771ed995921df7a5acc383',
    messagingSenderId: '925330772922',
    projectId: 'radioone-9562f',
    authDomain: 'radioone-9562f.firebaseapp.com',
    storageBucket: 'radioone-9562f.appspot.com',
    measurementId: 'G-S183RC160W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPxXfWoQXKxkfHNiZEdKLjCLd9AZ4bgpw',
    appId: '1:925330772922:android:0df234080cc9b6c9acc383',
    messagingSenderId: '925330772922',
    projectId: 'radioone-9562f',
    storageBucket: 'radioone-9562f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAK9AV1zaJj9G6Ob8bD4RwJo4yT2dGeYE4',
    appId: '1:925330772922:ios:eca00591b32c6627acc383',
    messagingSenderId: '925330772922',
    projectId: 'radioone-9562f',
    storageBucket: 'radioone-9562f.appspot.com',
    androidClientId: '925330772922-dl169dfq9f1ougt2puhhdoqp24j4jlvq.apps.googleusercontent.com',
    iosClientId: '925330772922-960j7skr8ji690fio9pasvv56svq6c2h.apps.googleusercontent.com',
    iosBundleId: 'com.example.raydeoOne',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAK9AV1zaJj9G6Ob8bD4RwJo4yT2dGeYE4',
    appId: '1:925330772922:ios:eca00591b32c6627acc383',
    messagingSenderId: '925330772922',
    projectId: 'radioone-9562f',
    storageBucket: 'radioone-9562f.appspot.com',
    androidClientId: '925330772922-dl169dfq9f1ougt2puhhdoqp24j4jlvq.apps.googleusercontent.com',
    iosClientId: '925330772922-960j7skr8ji690fio9pasvv56svq6c2h.apps.googleusercontent.com',
    iosBundleId: 'com.example.raydeoOne',
  );
}
